# Generated by Django 5.2 on 2025-04-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                ("slug", models.SlugField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=50)),
                ("content", models.TextField()),
            ],
        ),
    ]
