# Generated by Django 5.2 on 2025-06-24 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='navpage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
