name: Publish
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install
        run: uv sync --locked --all-extras --dev

      - name: Load Data
        run: |
          uv run manage.py migrate
          uv run manage.py loaddata data.json
      
      - name: Distill
        run: uv run manage.py distill-local distill-output/ --force --exclude-staticfiles
        env: 
          SITE_URL: ${{ vars.SITE_URL }}

      - name: Static files
        run: |
          mkdir -p ${{ env.STATIC_ROOT }}
          uv run manage.py collectstatic -i admin/
        env:
          STATIC_ROOT: distill-output/static/


      - name: Upload as Artifact
        id: upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: distill-output/
    
  deploy:
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4